# SPDX-FileCopyrightText: 2022 Nicolás Alvarez <nicolas.alvarez@gmail.com>
# SPDX-License-Identifier: CC0-1.0

PostInstallScripts:
    krita-plugins: build-tools/ci-scripts/build-plugins.py

Options:
    use-ccache: True
    use-asan: False
    run-gcovr: False
    per-test-timeout: 4:00
    cmake-options: '-DKRITA_ENABLE_PCH=OFF -DFOUNDATION_BUILD=ON'
    tests-run-in-parallel: True
    ccache-large-cache: True
    run-cppcheck: True
    cppcheck-ignore-files:
        - libs/pigment/KoAlphaMaskApplicatorFactory.cpp
    force-build-target: all
    force-install-target: install
